@base_url=http://localhost:9000
@access_token={{authenticate.response.body.accessToken}}

# @name create_account
POST {{base_url}}/accounts
Content-Type: application/json

{
  "name": "Deivison Resende",
  "email": "deivison@email.com",
  "password": "123456"
}

###

# @name authenticate
POST {{base_url}}/sessions
Content-Type: application/json

{
  "email": "deivison@email.com",
  "password": "123456"
}
###

# @name create_question
POST {{base_url}}/questions
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Título de uma pergunta",
  "content": "Porquê?"
}
###

# @name show_recent_questions
GET {{base_url}}/questions?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{access_token}}
